### ISSUE TITLE
Message "id" and text "id" contains slash /

### ISSUE THREAD

**Issue by avdnick** [andris9/imapapi#12]
Thank you very much for this tool. 
I 'm trying the imap api for the last week now and so far it looks very promising for my project. 
But as of today any new message i get. their id and their text id are containing a slash /. And i can't use the ids to make request for individual message or message's text. I get status 404. Not Found.
I took a look on the code to try to understand how the id is created with no luck. As i understand it the id is a combination of message's uid, mailbox and something else?
Is it really a problem for the id to contain a slash or is it normal and there is another way to overcome this "inconvenient" when making a request for this particular id?
Would be practical to make a request for a message using it's uid and path as a parameter?

**To Reproduce**
1 . Make a request for a list of messages for Inbox. I get the list correctly. 
2. Then i copy the "id" (AAAAAQAA9/g) of the message i am interesting in and make a new request for the individual message info ( ​/v1​/account​/{account}​/message​/{message}).
3. Get status code 404 Not Found.
4. Same when requesting text with it's id "AAAAAQAA9/iTkaExkJA"

**Comment by andris9** [comment]
This is clearly an issue. I think you should be able to use urlencoded values, eg "AAAAAQAA9/%2Fg" but this is inconvenient. I'll look into it, how to fix the ID values

**Comment by avdnick** [comment]
I tried with urlencoded %2F but i get a status code 400 Bad Request and message: "\"message\" must be a valid base64 string"

**Comment by andris9** [comment]
This is now fixed. It was a bug about converting base64 to "URL safe" format were slashes were not properly converted. If you replace slashes in your local ID versions with underscores then you should be able to use these ID values with latest version of IMAP API
