### ISSUE TITLE
Can we able to get webhooks events for only incoming messages. 

### ISSUE THREAD

**Issue by vinodhreddygs** [andris9/imapapi#13]
Hi @andris9 ,

Now in my application Iam getting the all  events through webhooks like "messageNew", "messageUpdated" and "messageDeleted" etc. Is it possible to get only specific events like "messageNew"?. So I can minimize the unnecessary webhooks  triggers call which I don't want in my web application.
Please reply me.

Thanks in advance.

**Comment by andris9** [comment]
Yes, this is planned, there is going to be an option to limit which kind of notifications are sent. Can not say ETA for this as I'm busy with other things right now.

**Comment by vinodhreddygs** [comment]
Thanks @andris9 for the quick reply. If can't  limit which kind of notifications are sent then, is it possible to receive notifications only for the specific domains?.

**Comment by andris9** [comment]
This is available from v1.4.2. Event types can be set globally but not per account.

<img width="772" alt="Screenshot 2020-12-18 at 11 00 32" src="https://user-images.githubusercontent.com/132242/102595512-596ce600-4120-11eb-92a1-dd3a0ec13e0c.png">
