### ISSUE TITLE
Get all unseen messages from a given date 

### ISSUE THREAD

**Issue by vinodhreddygs** [andris9/imapapi#16]
Hi @andris9 ,

Can we able to query to get all unseen messages (inbox) from a given date. If so, please provide me a API for that.
example: Get all unssen messages since last week.

Thanks in advance.

**Comment by andris9** [comment]
Date as search option is not yet supported. Currently supported search params can be found [here](https://github.com/andris9/imapapi/blob/516d9f30d7079290202701fed575f81c53ba98a7/workers/api.js#L1020-L1033).

You can use current search options like this:

```
$ curl "http://localhost:4452/v1/account/gmail/messages?path=INBOX&search[unseen]=true
```
