### ISSUE TITLE
Severe bug: On un-reading email, the event has the different mssageId instead the one actually it is.

### ISSUE THREAD

**Issue by vinodhreddygs** [andris9/imapapi#17]
Hi @andris9 ,

Whenever I unread an email, the event which I get through webhooks has a different messageId.
Due to that, I can't able to get the content of the email on which actually update event is triggered.
Please let me know what is the reason for this. This is causing severe issues in my application.

Thanks in advance.

**Comment by andris9** [comment]
Are you using Gmail or Gsuite? You have to perform all changes against messages in the “All messages” folder, not in actual folders. It’s the same message but has different id’s depending from the folder you are using.

**Comment by vinodhreddygs** [comment]
@andris9 I'am using Gmail.
How do I specify to get email from specific folder (i.e. All message) ?

This is the GET API to get the email information based on the messageID 
`/v1/account/{account}/message/{message}`  Where should I specify to retrieve message from specific folder?

**Comment by avdnick** [comment]
@vinodhreddygs Hi,
I think @andris9  means to use `/v1/account/example/messages?path=INBOX` and replace 'INBOX' with '[Gmail]/All Messages' to list the messages. And from there you get the messages you want to perfom a change.

**Comment by vinodhreddygs** [comment]
@avdnick Oh. thanks for your reply. I do that.
And also I have one more question i.e, Whenever webhooks triggers, I can see all the data storing in the Redis. How can I clear the data on Redis?

**Comment by vinodhreddygs** [comment]
> messages?path=INBOX

Hi @andris9 @avdnick ,
`/v1/account/example/messages?path=INBOX` : this API is to get all the  messages list from a particular folder as u mentioned like INBOX.
But there is one more API provided to get the specific email information based on the messageID i.e.` /v1/account/{account}/message/{message}` when I try to add qs syntax  to this API  i.e ` /v1/account/{account}/message/{message}?path=INBOX` , its gives bad request error.
Then what is the use of `/v1/account/{account}/message/{message}` if we can't get a message by giving the messageID that we get on any event trigger?

**Comment by andris9** [comment]
If you are using Gmail and want to use webhooks then you need to perform all your processing via the "All Mail" folder, not INBOX.

You can see from the `labels` property for the list of folders this email belongs to. Labels property includes as list of special-use labels and folder name strings for normal folders. Eg `{"labels": ["\\Inbox", "test"]}` means that message can be found both in INBOX and in a folder names "test". 

Gmail does not use the common one-folder/one-email model but one-email/multiple-folders and for each folder it has different id. The same message in different folders has the same `emailId` property but this is not the same as `id`.

**Comment by andris9** [comment]
If you do want to use INBOX instead of All Mail then you can match changes received via webhooks using the `emailId` property as this is always the same no matter what folder is used.

**Comment by vinodhreddygs** [comment]
> If you are using Gmail and want to use webhooks then you need to perform all your processing via the "All Mail" folder, not INBOX.
> 
> You can see from the `labels` property for the list of folders this email belongs to. Labels property includes as list of special-use labels and folder name strings for normal folders. Eg `{"labels": ["\\Inbox", "test"]}` means that message can be found both in INBOX and in a folder named "test".
> 
> Gmail does not use the common one-folder/one-email model but one-email/multiple-folders and for each folder it has different id. The same message in different folders has the same `emailId` property but this is not the same as `id`.

@andris9 do you mean that I need to get the all the messages in the folder "All Mail' and then i need to filter  the email which I want based on messageID?
Can't I get mail by messageID from "All Mail" folder using `/v1/account/{account}/message/{message} ` or I should do any modification to this API?

**Comment by andris9** [comment]
You can use `/v1/account/{account}/message/{message}` (where `{message}` is `data.id` value from the webhook JSON) to fetch message data. But if you have previously fetched the same message from INBOX, then `{message}` is different (one is for the message form INBOX and the other is for the message in All Mail). In the end it's the same email, so for example marking message as seen using All Mail id marks the same message as seen in INBOX.

**Comment by vinodhreddygs** [comment]
@andris9 All the message APIs that provided in the Swagger API docs will fetch/get messages or Attachments against the "All Mail" folder?
Please refer below screenshot:
![image](https://user-images.githubusercontent.com/37541181/82875129-9f7c1580-9f54-11ea-8c37-5877a7d3ff47.png)

**Comment by andris9** [comment]
`{message}` has folder path encoded into it, this is how IMAP API knows from which folder to look the message for. INBOX and All Mail are different folders and the same message has different UID value in these folder, so the same message can have multiple valid `{message}` values - one for each folder the message can be found in. The only thing that is consistent is `emailId` value but you can't use this for API calls.

**Comment by andris9** [comment]
So to answer your initial question, having different message id values is OK as message id value depends on the folder this message data was fetched from. Use `emailId` to match messages from IMAP API against your local copy.

**Comment by vinodhreddygs** [comment]
@andris9 on Flags update(i.e. On unread the mail), webhooks are not triggering, due to that I can't able to handle the events on flags update in my application.
Please let me know, is there any reason for this.
