### ISSUE TITLE
[doubts]: Message ID and Attachment ID is unique for all the messages in Gmail account?

### ISSUE THREAD

**Issue by vinodhreddygs** [andris9/imapapi#19]
Hi @andris9 ,

I have few questions that listed below:
1. Whenever I get a new message notification in my application from the IMAP API webhooks,
 I'am going to store the new message ID (i.e data.id) and Attachment ID(i.e.attachments[0].id) into my database. Using these messageID and attachmentID, I'am trying to fetch those email information in the future by making use of `GET :
​/v1​/account​/{account}​/message​/{message}` and `GET:
​/v1​/account​/{account}​/attachment​/{attachment}` respectively.
**Here my question is, these  messageID and attchamentID will be unique in future as well right?** otherwise there might be possible of fetching of wrong information for the given messageID and attachmentID. It leads to more issues.
2. Using query search options, can I get a all the messages received in last 24 hours from a particular domain only.
 ex: Get all received messages in last 24 hours for the domain `outlook.com` by using like this `$ curl "http://localhost:4452/v1/account/gmail/messages?path=INBOX&search[unseen]=true`

Thanks.

**Comment by andris9** [comment]
1. These id values are unique for an account. Two different accounts can have the same id pointing to different messages/attachments but inside an account this value is immutable and unique. Such id is valid as long as the messages to it refer exists and is never reused.
2. Currently no as search options are fairly limited at this point, there are going to be more search options in the future.

**Comment by andris9** [comment]
@vinodhreddygs actually it turned out to be quite easy to add the missing search options if using POST instead of GET. So I created a new API endpoint for searching and moved search request options from message listing to this new endpoint. You can achieve your query like this:

```
curl -X POST "http://127.0.0.1:3000/v1/account/test/search?path=INBOX&page=0&pageSize=20" -H "accept: application/json" -H "Content-Type: application/json" -d '{
  "search": {
    "since": "2020-05-27",
    "from": "@outlook.com"
  }
}'
```

**NB!** IMAP searches use dates, not date time values and the exact timestamp is selected by the server. So if you want to get the messages of last 24 hours, then you need to fetch messages for the last few days and filter results on your application by the message date value.

**Comment by vinodhreddygs** [comment]
@andris9  thanks!! for this API endpoint. But I don't see this API in your Swagger IMAP API docs. 
And It's really helpful **If you could provide what all the search options can give to the above end point.**
**Can I give the multiple domains to the search option `from` ?** like below: 

```
curl -X POST "http://127.0.0.1:3000/v1/account/test/search?path=INBOX&page=0&pageSize=20" -H "accept: application/json" -H "Content-Type: application/json" -d '{
  "search": {
    "since": "2020-05-27",
    "from": ["@outlook.com", "@gmail.com"]
  }
}'


```

**Comment by andris9** [comment]
You have to upgrade IMAP API to v1.3.0, then the new endpoint appears in Swagger as well.

<img width="586" alt="Screenshot 2020-05-29 at 12 18 26" src="https://user-images.githubusercontent.com/132242/83243451-96828280-a1a6-11ea-8e17-4778dcdf82f6.png">

You can not use multiple from addresses, it is a simple partial match search.

**Comment by vinodhreddygs** [comment]
@andris9  I have connected IMAP by running the command that you have given in this documentation. i.e. `$ npx imapapi --dbs.redis="redis://127.0.0.1:6379"`
When I restarted this command on server it's running on the latest version ` v1.3.0` .
Here my concern is, I have written this code based on the current version. What if any API got changes for the future versions? then, my code will break.
Is there any option to run the  command `$ npx imapapi --dbs.redis="redis://127.0.0.1:6379"`  on a particular version of IMAP? or any other way to over come the version issue?

**Comment by vinodhreddygs** [comment]
Hi @andris9 ,
Queries On using `POST : /v1​/account​/{account}​/search` :
1. The list of messages that we get using this API does n't have attachments property in the mail information. For Each mail we need to make a call to `GET : /v1/account/{account}/message/{message}` from that, we need to get attachments using `GET /v1/account/{account}/attachment/{attachment}`. Can't you include attachments property in the listing itself?

2. When I make a call to `/v1/account/' + accountId + '/search?path=INBOX&page=0&pageSize=20` , it gives response as there are 3 pages, and in the page 1(i.e. page index=0) have 107 messages but when I make a call to get 2nd page to `/v1/account/' + accountId + '/search?path=INBOX&page=1&pageSize=20` it has 169 messages. 
Here my question is, when we have multiple pages, don't we have equal number of messages in each page since I have given `pazeSize = 20 ` ?

3. In the messages list, the `message date value`  will be in UTC timezone? and also `search option 'since'` should give in UTC string format?
