### ISSUE TITLE
How to run on a particular API version

### ISSUE THREAD

**Issue by vinodhreddygs** [andris9/imapapi#20]
Hi @andris9 ,

I have connected IMAP by running the command that you have given in this documentation. i.e. `$ npx imapapi --dbs.redis="redis://127.0.0.1:6379"`
When I restarted this command on server it's runs on the latest version `v1.3.0` .
Here my concern is, I have written this code based on the current version. What if any APIs gets changes for the future versions? then, my code will break.
Is there any option to run the command `$ npx imapapi --dbs.redis="redis://127.0.0.1:6379"` on a particular version of IMAP? or any other way to over come the version issue?

**Comment by andris9** [comment]
Run

```
npx imapapi@1.2.3
```

Where 1.2.3 is the version number
