### ISSUE TITLE
Throwing Gateway time-out (504 status) error for multiple calls to the IMAP APIs

### ISSUE THREAD

**Issue by vinodhreddygs** [andris9/imapapi#22]
Hi @andris9 ,
I'am getting status error 504 i.e. `Gateway Time-out` in the following scenario's :
1. When I try to fetch mails which received in last few days (there are more number of mails in the All Mail folder), I need to make a multiple API calls by giving page index to this API : `http://127.0.0.1:3000/v1/account/123456/search?path=[Gmail]/All Mail&page=0&pageSize=1000
` at that time Iam getting 504 status Error.

2. When I try to `fetch a attachment by attachment-id using promise collection`. Here also I'am getting the 504 status error for some times. 

**Is there any API call limits to the IMAP APIs?**

**Comment by sandro971** [comment]
Same ! But with 
`{
    "error": "No active connection to requested account. Try again later.",
    "statusCode": 503
}`

I think i was to abord imapapi from my project

**Comment by sandro971** [comment]
Just don't use this in production

**Comment by andris9** [comment]
Calls per account are executed in order, so do not run multiple commands at once against the same account as while the first API command is executed, the others time out.
