### ISSUE TITLE
How to run in different port instead of 3000 or run multiple instance 

### ISSUE THREAD

**Issue by Pankaj-Pippin** [andris9/imapapi#23]
**Is your feature request related to a problem? Please describe.**
I want to run 2 or more instance in same server however its service only with port 3000  

**Describe the solution you'd like**
I think we should have full control instead of hard-coded port setting using command line or config file.

**Describe alternatives you've considered**
I tried to find the port code on node modules but unable to find it but in repository we can see that config.

Any help on this will surely help us 

Thanks

**Comment by andris9** [comment]
Port number is configurable, see https://github.com/andris9/imapapi#config-mapping
