### ISSUE TITLE
Account filters

### ISSUE THREAD

**Issue by mrkswrnr** [andris9/imapapi#24]
**Is your feature request related to a problem? Please describe.**
We are using a catch-all gmail account (Delivered-To != To) and triggering webhooks for all incoming emails would be too much. There is only one imap account for multiple mail-aliases. 

**Describe the solution you'd like**
I would like to specify a filter when creating an account to only retrieve mails with a To-Header matching a string or maybe even a regex pattern. Maybe it would also make sense to filter additional headers.

**Describe alternatives you've considered**
Alternative would be a possibility to create webhooks for specific mailboxes.

Thank you for your great work!

**Comment by andris9** [comment]
Sorry for long delay. Custom filtering is not planned. What you can do though is to filter on your own side. You can configure IMAP API to only send webhooks about new messages and include 'Delivered-To` header as part of the webhook data. Then you could drop all webhooks immediately that do not match your criteria, no need to make any additional requests to find out details about the message.

Example for configuring IMAP API to include specific headers in the webhook:

<img width="725" alt="Screenshot 2020-12-21 at 12 35 57" src="https://user-images.githubusercontent.com/132242/102776972-5a0fb180-4398-11eb-8888-f461a2dc5679.png">
