### ISSUE TITLE
[Severe bug]: POST API:  ​/v1​/account​/{account}​/search does not give proper search result for the domain

### ISSUE THREAD

**Issue by vinodhreddygs** [andris9/imapapi#26]
Hi @andris9 ,
When I call a post api `​/v1​/account​/{account}​/search` with filters like:
` {
"search":{
"from:"@pippintechnologies.com"
}
}` 
The resulted filter mails not only contains the mail received from domain `@pippintechnologies.com`, other domain mails like `@gmail.com`  will also be including,
please look for the below screenshot for reference:
![image](https://user-images.githubusercontent.com/37541181/87762002-0371da80-c830-11ea-8d1d-4eb02dbd12ea.png)

Any help on this will surely helps us!
Thanks.

**Comment by andris9** [comment]
Seems to be a bug with IMAP range request compilation where too large range is used, will look into it

**Comment by vinodhreddygs** [comment]
> Seems to be a bug with IMAP range request compilation where too large range is used, will look into it

You can see in the above attached image, I applied filter for domain `@gmail.com` 
(i.e. { "search":{ "from:"@pippintechnologies.com" } }) but the resulted mails contains `@pippintechnologies.com `  domain mails too.
