### ISSUE TITLE
Provide docker compose file and docker image for simple deployment

### ISSUE THREAD

**Issue by MiffyLiye** [andris9/imapapi#28]
**Is your feature request related to a problem? Please describe.**
For QA to use this tool, it would be complex to setup the environment with many npm commands.

**Describe the solution you'd like**
We can provide a docker compose file and a docker image, then QA can setup the environment with one single command
```
docker-compose up -d
```

Ref:
https://github.com/MiffyLiye/imapapi/blob/master/Dockerfile
https://github.com/MiffyLiye/imapapi/blob/master/docker-compose.yaml

**Comment by andris9** [comment]
Docker support is now [built in](https://github.com/andris9/imapapi#docker) (ended up using a different solution)
