### ISSUE TITLE
Emails not threaded

### ISSUE THREAD

**Issue by pshah123** [andris9/imapapi#29]
While listing messages lists all messages correctly in chronological order, it doesn't thread any emails. Since it is paged this makes it nearly impossible to build a message thread syntactically.

I'm wondering if this is intended behaviour + if so, is threading on the roadmap?

**Desktop (please complete the following information):**
 - OS: WSL 2

**Comment by andris9** [comment]
Threading support will come eventually but can't give any ETA as it is not in development yet.
