### ISSUE TITLE
Mailboxes do not resync with servers with no CONDSTORE CAPABILITY eg office365

### ISSUE THREAD

**Issue by kusmira** [andris9/imapapi#30]
As the topic. 
The server does not return the HIGHESTMODSEQ parameter in SELECT / EXAMINE queries. 
In the mailbox.js on line 223:

`status.highestModseq = status.highestModseq || false;`

causes status.highestModseq to always be false.

Code on line 242:

```
if ((! status.messages &&! storedStatus.messages) || status.highestModseq === storedStatus.highestModseq) {
    // no reason to sync
    return true;
}
```

causes synchronization to never take place.

The simplest way for me was to change it to:

```
if ((! status.messages &&! storedStatus.messages) || (status.highestModseq! = false && status.highestModseq === storedStatus.highestModseq)) {
    // no reason to sync
    return true;
}
```

Regards Adam

**Comment by andris9** [comment]
Thanks! Fixed in latest version.
