### ISSUE TITLE
Payload content length greater than maximum allowed: 1048576 ?

### ISSUE THREAD

**Issue by andiksetyawan** [andris9/imapapi#32]
I send file attachment just 1MB file from multer buffer, but error 
`
{
      statusCode: 413,
      error: 'Request Entity Too Large',
      message: 'Payload content length greater than maximum allowed: 1048576'
}`

I read in the documentation that the maxLength file limit: 5242880. what's wrong ? . Thank you for your help.

**Comment by andris9** [comment]
Fixed in latest v1.3.5
