### ISSUE TITLE
Production Use?

### ISSUE THREAD

**Issue by aibarra11** [andris9/imapapi#37]
Sorry, i know this isn't a bug, not sure where to ask these questions
Has this been used in production? 
About how many users?
Are there any known concerns/issues for not running this in production?
(lets assume the external authentication is solid, redis is an enterprise deployment, mail servers are our own and scaled properly)
We have some very specific requirements for a new email system and this looks like a good piece of the puzzle. Potentially tens of thousands of users.

**Comment by andris9** [comment]
IMAP API is not well tested in production. There are smaller installations out there but I do not know the details. IMAP API grew out from the [WildDuck IMAP server](https://docs.wildduck.email/#/) project which is quite battle tested by now, both share the same IMAP parsing and compiling core. 

If setting up a larger installation of IMAP API then you'd be the first, so I can't guarantee how well it would perform. Your alternative would be to use [Nylas Email API](https://www.nylas.com/products/email-api/) which is well tested and production ready but much more expensive. If you decide to go with IMAP API but are worried about issues that might occur then there's an option to get a [support plan](https://postalsys.com/plans) for my email libraries that also covers IMAP API.

**Comment by aibarra11** [comment]
Thanks for the info! We were looking into Nylas, gets pretty expensive and doesn't meet all of our requirements. Will checkout WildDuck

**Comment by marnickmenting** [comment]
We are using it now for a few months in production for our helpdesk SaaS product, and must say it is pretty stable. We did not encounter problems or hick-ups so far. We have it connected to one mailbox of our own to receive webhooks in our Laravel application within seconds.
