### ISSUE TITLE
How to submit message directly to an mailbox besides INBOX

### ISSUE THREAD

**Issue by ernaneluis** [andris9/imapapi#40]
**Is your feature request related to a problem? Please describe.**
Looking in away to avoid to request the the endpoint `PUT /v1​/account​/{account}​/message​/{message}​/move` 

**Describe the solution you'd like**
Send an message directly to an specific mailbox, maybe a new param at /submit endpoint

**Comment by andris9** [comment]
There is a new API  endpoint in v1.4.0 that allows you to upload the message into a specified path.

<img width="598" alt="Screenshot 2020-12-17 at 15 27 49" src="https://user-images.githubusercontent.com/132242/102493849-7354ed00-407c-11eb-94ba-c210a042e89a.png">
