### ISSUE TITLE
How to get all messages sent by account?

### ISSUE THREAD

**Issue by ernaneluis** [andris9/imapapi#42]
**Is your feature request related to a problem? Please describe.**
I would like to query all messages that an account has sent ( as "from")

**Describe the solution you'd like**
Query by FROM on /search endpoint would also consider the messages sent by account not only received

**Describe alternatives you've considered**
Include in the TO array, the account set in FROM (send to myself)

**Comment by andris9** [comment]
You should be able to do this when searching from the Sent Mail mailbox.
