### ISSUE TITLE
Search by bcc not working

### ISSUE THREAD

**Issue by thorstenkramm** [andris9/imapapi#43]
**Problem**
Searching emails by bcc always returns an empty result.

**To Reproduce**
Send an email to some imap inbox using bcc, for example
`date | mail -s test mainemail@example.com -a "bcc: bcc-email@example.com"` 
Access the IMAP inbox with the imapi and use a bcc search filter on `POST <account>/search?path=INBOX`
```
{
  "search": {
    "bcc": "bcc-email@example.com"
  }
}
```
You won't find the email.

**Expected behavior**
All emails having the address in the bcc header are in the result set.

**Comment by andris9** [comment]
Are you sure these messages have a Bcc header field?

**Comment by tientp-floware** [comment]
Hi @andris9 ,
I have the same case. And sure I have attribute bcc in the header.
