### ISSUE TITLE
Some messageIds contain forward slash '/' and fails api requests that use messageId as path parameter

### ISSUE THREAD

**Issue by VarunRaj7** [andris9/imapapi#44]
**Describe the bug**
Some messageIds contain forward slash '/'. And fails when api calls when it is used as the path parameter even when encodeURIComponent(messageId). 

**To Reproduce**
I think to reproduce the behaviour try to fetch as many messageIds as possible and check. There's no direct way to reproduce.

**Expected behavior**
Expecting all messageId's to be free of '/'.

**Desktop (please complete the following information):**
 - OS: iOS

**Additional context**
Also checked via swagger. It fails there as well as shown in the screenshot.

<img width="544" alt="IMAP API messageIds" src="https://user-images.githubusercontent.com/48964525/101725644-055a6580-3a7f-11eb-85df-903eab59be2d.png">

<img width="1181" alt="IMAP API Server Swagger" src="https://user-images.githubusercontent.com/48964525/101725665-0d1a0a00-3a7f-11eb-9109-aa18fa14eee7.png">

**Comment by andris9** [comment]
Just to check, are you using the latest version of imap api? Does it work if you replace the slash with `%2F` ?

**Comment by VarunRaj7** [comment]
It doesn't work when replaced with the %2F....

**Comment by andris9** [comment]
what is the version number of IMAP API? is it v1.3.5?

**Comment by VarunRaj7** [comment]
Thanks for clarification. I am using the older version. In the newer version 1.3.5, the '/' is replaced with the '_'.

**Comment by andris9** [comment]
Yes, this issue is fixed in latest versions. Just wanted to confirm that it’s not something else.

**Comment by VarunRaj7** [comment]
On a different note: the newer version takes longer (~5 min) to connect to the account!! Could you please suggest the lighter version that has this bug fixed.
