### ISSUE TITLE
Connecting an account takes longer than 5min. 

### ISSUE THREAD

**Issue by VarunRaj7** [andris9/imapapi#45]
**Describe the bug**
After initial setup of an account. The time taken for the account to move state from 'init' to 'connected' takes almost 5 minutes. Is this expected?

**To Reproduce**
Steps to reproduce the behavior: A simple account creation process.

**Expected behavior**
Expected to move account state from 'init' to 'connected' quickly. This can be seen in the previous versions such as '1.1.0'

**Desktop (please complete the following information):**
 - OS: iOS Big Sur

**Additional context**
I am using the latest version of the imapapi v1.3.6.

**Comment by andris9** [comment]
Initial sync time depends on the server software, which extensions are supported by the server, mailbox size, folder count etc.
