### ISSUE TITLE
Office 365 webhooks

### ISSUE THREAD

**Issue by atekk96** [andris9/imapapi#47]
When I send a message through office 365 mailbox webhook comes with long delay, around 15-20 seconds. Is there any way to get those webhooks almost instantly? Gmail works much faster.

**Comment by andris9** [comment]
Every server operates differently. Not much to do about that.

**Comment by atekk96** [comment]
I would like to specify my question.  I am sending a message through imapapi. I thought that webhook would show up almost instantly after sending a message but it shows up with a delay(as I mentioned earlier). What is the reason behind this delay? After sending a message is there a forced synchronization?
