### ISSUE TITLE
502 when trying to create an account

### ISSUE THREAD

**Issue by faradaytrs** [andris9/imapapi#49]
**Describe the bug**

I tried to create account throught /v1/account and got 502

In logs i see 
 is.

**To Reproduce**
1. Install imapapi throught npm i -g imapapi on ubuntu with default redis server from apm
2. Make a request with curl
`curl -XPOST "http://127.0.0.1:3000" -H "content-type: application/json" -d '{"account":"faradaytrs@126.com","name":"faradaytrs@126.com","imap":{"auth":{"user":"faradaytrs@126.com","pass":"pass"},"host":"imap.126.com","port":993,"secure":true,"tls":{"rejectUnauthorized":false},"resyncDelay":900},"smtp":{"auth":{"user":"faradaytrs","pass":"pass"},"host":"smtp.126.com","port":443,"secure":true,"tls":{"rejectUnauthorized":false}}}'`
3. curl: (52) Empty reply from server
4. See logs and find 
`{"level":60,"time":1609315386333,"pid":78627,"hostname":"globus","tid":11,"msg":"unhandledRejection","err":{"type":"TypeError","message":"Cannot read property 'statusCode' of null","stack":"TypeError: Cannot read property 'statusCode' of null\n    at Request._finalize (/usr/lib/node_modules/imapapi/node_modules/@hapi/hapi/lib/request.js:497:31)\n    at Request._reply (/usr/lib/node_modules/imapapi/node_modules/@hapi/hapi/lib/request.js:434:18)\n    at Request._execute (/usr/lib/node_modules/imapapi/node_modules/@hapi/hapi/lib/request.js:280:14)\n    at processTicksAndRejections (node:internal/process/task_queues:93:5)"}}`
A clear and concise description of what the bug

**Expected behavior**
Expected normal behavior

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] OS: Ubuntu 20.04.1 LTS x86_64 Kernel: 5.4.0-58-generic
 - Browser [e.g. chrome, safari] curl, the same with edge and firefox
 - Version [e.g. 22] edge 87
 - 
**Additional context**

**Comment by andris9** [comment]
This happens when Hapi version is not compatible with Node version. You could try to upgrade IMAP API or downgrade Node to 14 (if you are using Node 15)
