### ISSUE TITLE
OFFICE365 - cannot download message by messsage_id

### ISSUE THREAD

**Issue by wciurzynski** [andris9/imapapi#53]
Version 1.4.6
After full sync of all emails from OFFICE365 I cannot download message by endpoint "/v1/account/{account}/message/{message_id}".

If I search mailbox (by IMAPAPI ) there is message with text.id: "AAAAAgAAJYCTkaExkaEykA" and uid: "9600".
GET "/v1/account/{account}/message/AAAAAgAAJYCTkaExkaEykA" returns "Requested message was not found".
After adding more logs I found that in file lib/mailbox.js in function "getMessage(message, options)" line imapClient.fetchOne(message.uid, fields, { uid: true }) returns false - messageData is set to false.

Could you help me with this ?

**Comment by avdnick** [comment]
I think the problem is that you are trying to get a message by text id
instead of message id

**Comment by wciurzynski** [comment]
I understand but I tried both - text.id and message_id and result is the same. But I notice that after some time all works, maybe after 30 minutes. Uid did not change.

**Comment by wciurzynski** [comment]
There is something strange with OFFICE365. Sometimes I cannot find message because imapClient.fetchOne(message.uid, fields, { uid: true }) returns false, sometimes the same uid return message but html and plain_text are empty. I started to save uid and mailbox from webhook and if text or html is empty string I connect mysql to OFFICE365 with IMAPClient (python - https://imapclient.readthedocs.io/en/2.2.0/), I fetch message (RFC822) by uid and retreive html or plain_text myself.

So IMAPAPI has some problems with OFFICE365 - did you run full tests for office365 ?

**Comment by wciurzynski** [comment]
Full sync by deleting and adding account helped - one message which I could not download text/html now there I can. I will check the rest of emails.

Why deleting and adding account helped ?

**Comment by andris9** [comment]
There is an improvement with Office365 compatibility in the latest version of IMAP API.
