### ISSUE TITLE
Production mode

### ISSUE THREAD

**Issue by ricus-zero2one** [andris9/imapapi#58]
Hi @andris9 

Quick one. Would it be possible to add in some production mode or some basic auth on the dashboard for when this is used in a live environment?

Currently the way I understand it, once you start the server you can just access it directly, giving you access to the settings where you can view (or change if you are being malicious) the webhook, and also the swagger docs which basically gives you root access to all mailboxes as you can query them and read all mail contents.

Right now the only way I can think of deploying it to live is to set up an instance on aws where the imap-api server will run, and then lock that down as much as possible to only be accessible by a specific server that needs to do api calls to it. And as I would need to see the interface for some scenarios, I would need to whitelist an ip or two to be able to access the dashboard.

Am I maybe understanding things wrong and there is a diff approach for going to live? It would be nice if there was an option to place the dashboard behind some basic auth, or disable swagger docs for live or something along those lines?

Any thoughts on this?

**Comment by andris9** [comment]
The correct way to run IMAP API would be to bind it to 127.0.0.1 (it's also the default) so it wouldn't be externally accessible and then configure Nginx/Apache/Caddy/HAProxy or similar in front of it as a proxy. This way you can handle all the security stuff (https, basic auth, ip restrictions etc) in the proxy. You can find an example Nginx config [here](https://github.com/andris9/imapapi/blob/master/systemd/nginx-proxy.conf)
