### ISSUE TITLE
Init Stage

### ISSUE THREAD

**Issue by ricus-zero2one** [andris9/imapapi#59]
Hi @andris9 

Not a bug report, but also not a feature request, more like a "General"

I've noticed that a mailbox seems to get 'stuck' on the init stage after first setup sometimes. Probably not stuck, but it will sit on the init stage for 45 minutes to an hour. I've noticed this for bigger mailboxes. What happens during the init stage that could be causing these delays?

I haven't waited it out yet, normally after about half an hour I will request a reconnect which sometimes gets the mailbox to the connecting then connected state, or sometimes if it really doesn't want to move, I remove and add that account back, and then it pretty quickly gets connected.

When setting up a new account, I set the syncsince to today or yesterday in an attempt to make the initial setup a bit faster, but I'm not sure if that actually makes a difference.

Any ideas on this long init stage? Should it just be waited out even if it takes longer than an hour?

Regards

**Comment by andris9** [comment]
IMAP API performs account indexing in the init stage and this might take some time, though in the range of 5 minutes, not an hour, so I’m not sure what actually happens there.

**Comment by HrithikMittal** [comment]
Hey, @ricus-zero2one try connecting the account with the field ``notifyFrom``. This field will contain the date in this format ``2021-02-23``. So Put the date of tomorrow. Try it once.

**Comment by ricus-zero2one** [comment]
@HrithikMittal I do make use of the `notifyFrom` when creating an account via the api. I select the current day, as I need to be able to test with new emails coming in, and thought setting it to tomorrow might only start sending webhooks from tomorrow.

@andris9 Some of our clients have hundreds (even one with more than 1k) of imap folders. I noticed during the init stage, the webhooks were getting sent for the account even though it is still in init, so it looks like messages are also processed during this stage maybe? 

This particular account was set up from the gui, so no option for syncSince. I noticed emails from 2019 coming in with the webhooks, does it default to just "all mail" when setting it up from the gui?

To try and summarize the questions here:
* Does emails get synced during the init stage? And from how far back as default?
* Does the email sync need to be completed to move to connected state? So for thousands of emails this can take quite some time? 
* If init needs to index the folders, would having hundreds of folders maybe impact that drastically?

**Comment by andris9** [comment]
* init stage syncs metadata for *all* (not actual content though, unless the message  is previously unseen) emails, otherwise it would not know which ones are *new* and which were *deleted*
* * notifyFrom* allows you to skip webhook notifications, nothing else. The GUI is a minimal API wrapper, mostly for demo purposes, for anything more serious you're supposed to use the API directly
* going through hundreds of folders definitely makes things slower. IMAP does not allow parallel access to folders (except for Gmail that has the "All mail" folder), you need to check all folders one-by-one

**Comment by andris9** [comment]
`notifyFrom` handling was buggy and older messages than needed were indexed making init very slow. Now this is fixed so when setting up a new account, then at least the first connection should be way more faster than previously.
