### ISSUE TITLE
Should be possible to update Setting w/o Webhook URL

### ISSUE THREAD

**Issue by rafalf** [andris9/imapapi#60]
**Describe the bug**
Should be possible to update Setting w/o Webhook URL

**To Reproduce**
1. Go to IMAP API ->  'Settings'
2. Attempt to add an account in logs section

**Expected behavior**
it gets added

**actual**
Not saved because Webhook URL is blocking the form to submit 

is there any workaround to get it added directly in the setting file?

**Comment by andris9** [comment]
Well, the UI is just a wrapper around the API so you can edit all settings directly with API calls. You can also edit settings through the Swagger page. For example to change the number of log lines, search for the `POST /v1/settings` section and use the following payload:

```
{
  "logs": {
    "maxLogLines": 600
  }
}
```
