### ISSUE TITLE
Can't pass authToken in smtp

### ISSUE THREAD

**Issue by laurentsenta** [andris9/imapapi#61]
Hi there, thanks for maintaining and sharing this tool,

**Describe the bug**
I try to set up an account with imap and SMTP to connect to Gmail. Using their OAuth script I generated an access token.
It seems to work fine with imap, but when I try to set the SMTP auth I get the following error:

```
{"statusCode":400,"error":"Bad Request","message":"Invalid input","fields":[{"message":"\"smtp.auth.pass\" is required","key":"pass"}]}
```

With a password, for the sake of completeness:

```
{"statusCode":400,"error":"Bad Request","message":"Invalid input","fields":[{"message":"\"smtp.auth.pass\" is not allowed to be empty","key":"pass"},{"message":"\"Authentication\" contains a conflict between exclusive peers [pass, accessToken]","key":"auth"}]}%                                                                                                                                       
```

**To Reproduce**

```sh
API_PORT=8123 npx imapapi --dbs.redis="redis://127.0.0.1:6379" --api.port=8123 --api.host=127.0.0.1

curl -X POST "http://127.0.0.1:8123/v1/settings" -H  "accept: application/json" -H  "Content-Type: application/json" -d "{  \"webhooks\": \"${WEBHOOK_API}"}"

DATA=$(cat <<EOF
{
  "account": "${GMAIL_EMAIL}",
  "name": "${GMAIL_EMAIL}",
  "copy": true,
  "notifyFrom": "2021-03-03",
  "imap": {
    "auth": {
      "user": "${GMAIL_EMAIL}",
      "accessToken": "${GMAIL_ACCESS_TOKEN}"
    },
    "host": "imap.gmail.com",
    "port": 993,
    "secure": true,
    "tls": {
      "rejectUnauthorized": true,
      "minVersion": "TLSv1.2"
    },
    "resyncDelay": 900
  },
  "smtp": {
    "auth": {
      "user": "${GMAIL_EMAIL}",
      "accessToken": "${GMAIL_ACCESS_TOKEN}"
    },
    "host": "smtp.gmail.com",
    "port": 587,
    "secure": false,
    "tls": {
      "rejectUnauthorized": true,
      "minVersion": "TLSv1.2"
    }
  }
}
EOF)

echo "${DATA}"

curl -X POST "http://127.0.0.1:8123/v1/account" -H "accept: application/json" -H "Content-Type: application/json" -d "${DATA}"
```

**Expected behavior**

I expect the API to be OK with my payload and let me send an access token without pass.

**Screenshots**

In swagger, there is a "Model1" that looks buggy:
<img width="1396" alt="Screenshot 2021-03-03 at 13 23 44" src="https://user-images.githubusercontent.com/1136669/109805508-cf62f280-7c23-11eb-9c80-0a16efd63212.png">

**Desktop:**

macos, node 12.20

**Comment by laurentsenta** [comment]
Naive fix from my superficial understanding: https://github.com/andris9/imapapi/pull/62/files

**Comment by andris9** [comment]
This is probably not what you want as Gmail accessTokens are valid for 1 hour only. This account can not reconnect once the token has expired. You should probably look into setting up an [authentication server](https://github.com/andris9/imapapi/blob/master/examples/auth-server.js) to manage OAuth tokens on your side.

**Comment by laurentsenta** [comment]
I just want to prototype and demo a feature, so I was fine with this approach,

I did fallback to your solution thanks for the advice, but this behavior still looks like a bug! :)

**Comment by andris9** [comment]
Yes, it's a bug. I haven't been able to accept your PR because of the pending [CLA requirement](https://github.com/andris9/imapapi/pull/62#issuecomment-789682206).

**Comment by laurentsenta** [comment]
Done!
