### ISSUE TITLE
Interact with labels through the API

### ISSUE THREAD

**Issue by laurentsenta** [andris9/imapapi#63]
**Is your feature request related to a problem? Please describe.**

I haven't found a way to add / delete / set labels using the API.

This is especially missing with Gmail:
when you move a message with the API, Gmail **adds** a label, so there is no way to really MOVE a mail to another folder.

**Describe the solution you'd like**

Right now, in the PUT message API, we can set flags:

```json
{
  "flags": {
    "add": [],
    "delete": [],
    "set": []
  }
}
```

Add the option to set labels,

```json
{
  "flags": {
    "add": [],
    "delete": [],
    "set": []
  },
  "labels": {
    "add": [],
    "delete": [],
    "set": []
  }
}
```

The rest of the API looks perfect,
the GET message returns flags and labels, and the webhook shows flags and label changes.

**Describe alternatives you've considered**

Deleting and recreating messages. That would be monstrous :)

Thanks again for sharing this API,
happy to help if needed.

**Comment by andris9** [comment]
This is now possible in v1.4.9
