### ISSUE TITLE
Message ID changes when e-mail is changed folder and back (Outlook)

### ISSUE THREAD

**Issue by marnickmenting** [andris9/imapapi#64]
First of all, great work on this library! We have been using it for months now and it is a crucial part of our application ecosystem.

**Describe the bug**
When a message on Outlook server is moved from INBOX to Archive and then back to INBOX, the 'id' is different. The webhook 'messageNew' is therefore fired again and data gets duplicated in our application.

**To Reproduce**
1. Add an Outlook (outlook.office365.com) account to IMAPAPI (I can provide you one if you need testing)
2. Let 'init' complete
3. Check 'id' field of last message with /messages?path=INBOX
4. Move e-mail in Outlook or Web Outlook to other folder, like Archive
5. Move e-mail back to INBOX again
6. Check message ID of the same e-mail as step 3, you will see the 'id' of message, attachments and text are changed.

**Expected behavior**
That the id of the same message in the same folder is always the same, and the webhook 'messageNew' therefore only fires ones.

**Additional context**
Looks related to https://github.com/andris9/imapapi/issues/17, but it is not about Gmail, and not about reading a specific folder instead of '[Gmail]All messages'. As far as I can see there is no 'All E-mail' folder in Outlook, to prevent the different message ID's in different folders.

**Possible solutions**
- The best way seems to me to keep the hashing of folder/message the same, but I don't know how that technically works.

- I might use the "messageId" data field in the format '<HE1PR0601MB20750BBC5A1A61F13EBE5CDFC76F9@HE1PR0601MB2075.eurprd06.prod.outlook.com>', but then we will need to setup a separate database to remember which id's are already processed or not and check them on incoming webhooks. I am not sure these are always unique though.

**Comment by andris9** [comment]
ID of a message points to a message object in the IMAP server and unfortunately IMAP does not keep track of copied/moved messages so when a message is added to a folder then it always gets a new ID - even if the same message has already "been" in that folder before. It is possible to make multiple copies of the same message and obviously these can not share the same ID. If you want to keep track of such messages then you should use the messageId approach that you described.

**Comment by marnickmenting** [comment]
Thanks for the fast reply, will keep track of the messageId in our application then.
