### ISSUE TITLE
Moving messages around ?

### ISSUE THREAD

**Issue by sadortun** [andris9/imapapi#65]
Hi,

What should we expect when an email is moved between two folders on the same account ? Is there a way to track this message by an ID? 

Follow up on question, let's say a user have two IMAP inboxes in his email client and he drags an email from `Account 1/INBOX` to `Account 2 / Archives` 

Is there a way to track that this is the same email being moved around ?

what kind of events should we expect from imapapi?

Thanks!

**Comment by andris9** [comment]
Moving a message in IMAP means 2 things:

1. the message is deleted from the source folder
2. it is aded to the destination folder as a new message

So you should get 2 unrelated events, one for the deleted message and one for the added message. This applies both when moving messages inside the same account and from one account to another.

Keeping track of the messages is the responsibility of the client as the server does not give out any indications. There is an exception though, for some servers IMAP API also shows a property `emailId` that is globally unique and does not change if you move messages around (except when you are moving a message from one email account to another) but this is limited to only a few servers as most do not support it (I think that it is mostly supported by Gmail/Yahoo, not by others), so you can't really rely on it unless you are building a Gmail-only service.

**Comment by marnickmenting** [comment]
See https://github.com/andris9/imapapi/issues/64 for similar question. The solution I chose was to keep track of the messageId in my own database which has a format like <AM9P195MB106335D9E62C0AB7CD3F34F6FB6C9@AM9P195MB1063.EURP195.PROD.OUTLOOK.COM> .
