### ISSUE TITLE
Pass in a complete configuration

### ISSUE THREAD

**Issue by laurentsenta** [andris9/imapapi#67]
**Is your feature request related to a problem? Please describe.**

At the moment, I use the docker container you provide to run my system,
when the container starts, I have to send HTTP requests to configure the webhook URL and the credentials URL.
(POST /v1/settings)

This means that the container has to be exposed to my host at some point,
it makes security less straightforward to configure 2 URLs.

**Describe the solution you'd like**

I'd rather be able to pass the URLs as parameters, such as
"--api.webhooks=myinternalapi:3000"
"--api.credentials=myinternalapi:3000"

This would fit nicely with docker compose networking, and simplify my ops script.

**Describe alternatives you've considered**

Sending POST requests, spinning up temporary containers just to send the request, etc.

**Additional context**

**Comment by andris9** [comment]
I added an option to provide prepared settings to IMAP API on application start. See the details [here](https://github.com/andris9/imapapi#prepared-settings). Requires IMAP API v1.5.0+
