### ISSUE TITLE
Detect event if user mark email as spam 

### ISSUE THREAD

**Issue by soumen-cn** [andris9/imapapi#68]
Hi

I need to detect the webhook event whenever a user manually moves a mail to Spam or mark it as spam. When I look at the webhook event response in such a scenario it is detected as `messageNew` in the Spam folder. So it is the same as if a mail lands on spam or the mail is marked as spam.

Response: 
```
{
	"account": "6d***5fa-******-****",
	"date": "2021-04-09T09:32:45.490Z",
	"path": "[Gmail]/Spam",
	"specialUse": "\\Junk",
	"event": "messageNew",
	"data": {
		"id": "AAAAAAAAAA",
		"uid": 10,
		"emailId": "Numeric Email ID",
		"threadId": "Numeric Thread ID",
		"date": "2021-04-09T09:19:17.000Z",
		"unseen": true,
		"size": 5487,
		"subject": "Mail Subject",
		"from": {
			"name": "Test User",
			"address": "Test user mail address"
		},
		"replyTo": {
			"name": "Test User",
			"address": "Test user mail address"
		},
		"sender": {
			"name": "Test User",
			"address": "Test user mail address"
		},
		"to": [{
			"name": "Recipient Name",
			"address": "Recipient mail address"
		}],
		"messageId": "<b0****bd9-****-****-****-*******@example.com>",
		"text": {
			"id": "AAAAAAAAA********",
			"encodedSize": {
				"plain": 77,
				"html": 164
			},
			"plain": "Body of the mail",
			"html": "<div>HTML content of the body</div>",
			"hasMore": false
		}
	}
}
```
How can I distinguish between a mail that automatically lands on spam and manually marked as spam and get details of it?

Thanks in advance

**Comment by andris9** [comment]
There is no 100% reliable way to detect if a message was moved to Spam by the user or by some other means. With Gmail the best approach would be tracking the `emailId` value. If you have seen the same `emailId` previously in some other folder and now it is added to Spam then there's a great probability that it was moved by the user. On the other hand if you have never seen this `emailId` before then it was added there most probably by Gmail's spam filter. Most other servers do not have such a globally unique email identifier like `emailId` but you can use `messageId` instead which is _usually_ unique but is not guaranteed to be so.
