### ISSUE TITLE
Customizable IMAP command timeout

### ISSUE THREAD

**Issue by leucos** [andris9/imapapi#69]
**Is your feature request related to a problem? Please describe.**

When using certain email providers (won't name _laposte.net_ them to protect the innocent), some IMAP commands take more than 10 secs to complete.

However, the command timeout is [hardcoded](https://github.com/andris9/imapapi/blob/c52fa165067829b4e5c6364919b31032a5f53d22/workers/imap.js#L512)  and does not seem configurable.

I am a JS nitwit so there might be a way to set `message.timeout` to prevent fallbacking to the default `10*1000`.

**Describe the solution you'd like**

Having a CLI flag/ENV var to set the timeout would be awesome.

**Describe alternatives you've considered**

Since we're building the container ourselves, we could patch at docker-build time; but this is not very maintainable.

**Additional context**

Sample timeout (`xyz` being a valid message ID):

```
$ curl -v "http://localhost:8888/v1/account/abc/message/xyz" | jq '.'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 127.0.0.1:8888...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8888 (#0)
> GET /v1/account/abc/message/xyz HTTP/1.1
> Host: localhost:8888
> User-Agent: curl/7.68.0
> Accept: */*
> 
  0     0    0     0    0     0      0      0 --:--:--  0:00:09 --:--:--     0* Mark bundle as not supporting multiuse
< HTTP/1.1 504 Gateway Timeout
< content-type: application/json; charset=utf-8
< cache-control: no-cache
< content-length: 94
< Date: Tue, 13 Apr 2021 13:07:28 GMT
< Connection: keep-alive
< Keep-Alive: timeout=5
< 
{ [94 bytes data]
100    94  100    94    0     0      9      0  0:00:10  0:00:10 --:--:--    23
* Connection #0 to host localhost left intact
{
  "statusCode": 504,
  "error": "Gateway Time-out",
  "message": "Timeout waiting for command response"
}
```

**Comment by andris9** [comment]
Yes, that's a valid concern, there are multiple reasons why commands might take a long time to complete. I added a configuration option so you could change the allowed duration (default is still 10 seconds). See the command timeout option [here](https://github.com/andris9/imapapi#config-mapping)

**Comment by leucos** [comment]
Wow, that was fast, thanks !
