### ISSUE TITLE
Why 

### ISSUE THREAD

**Issue by nhCoder** [andris9/imapapi#70]
`{"statusCode":504,"error":"Gateway Time-out","message":"Timeout waiting for command response"}`
Got this on multiple requests to API
I understand that it process IMAP requests serially not parallelly but it never releases the lock on mailbox..
The lock then never released and the same response every time, is there a way to fix it.

**Comment by andris9** [comment]
From the logs you should see what were the last commands issued by IMAP API before it got stuck. Could be a bug, could be intentional, hard to say based on that description.
