### ISSUE TITLE
Detect webhook event if email lands on SPAM

### ISSUE THREAD

**Issue by soumen-cn** [andris9/imapapi#71]
Hi @andris9 

Webhook event is working fine for INBOX, Sent, Draft and getting proper response. But if any mail lands on **SPAM** the webhook event is not called. If I move any mail from iNBOX to SPAM then only the webhook event is calling.

How can I get webhook event response if any email lands on SPAM by default?

**Comment by andris9** [comment]
Does it not work at all or is it with a delay? Spam messages should be detected in 15 minutes or so (`resyncDelay` option defaults to 15 minutes).

**Comment by soumen-cn** [comment]
Hi @andris9 

Last day I have received 3 SPAM mail in the mailbox but received 1 webhook event from one of them.
Today I have received a total of 5 mail-in SPAM but get only 2 webhook out of them. Webhook for other mails lost.
Working fine if mail lands on INBOX.

**Comment by andris9** [comment]
What IMAP server are you using? Gmail? O365? Something else?

**Comment by soumen-cn** [comment]
Hi @andris9 

This is happening with **`Gmail`**, not checked with the other servers yet.

**Comment by andris9** [comment]
Could you try again using the latest version on IMAP API? There is going to be a delay in detecting changes from the Spam folder but it should find all new emails eventually.

**Comment by soumen-cn** [comment]
Sure. I will try with the latest version and let you know.

**Comment by raduoprea** [comment]
@andris9 Even with the latest version, we are able to detect only a fraction of the emails in spam, even after a few days.

Have any pointers?

**Comment by andris9** [comment]
I guess what might happen is that IMAP API does not properly detect that there are changes in the spam folder. 

IMAP API should periodically run STATUS requests against other mailboxes. So could you check STATUS response for the spam folder before a spam message lands in it and also after spam message is in the spam folder.

```
tag STATUS \"[Gmail]/Spam\"
* STATUS ...
tag OK Success
```

If there is a difference in STATUS response, then look if IMAP API tries to open Spam folder or not

```
tag SELECT \"[Gmail]/Spam\
```

**Comment by andris9** [comment]
I've been trying to re-create the same situation and spam messages seem to be picked up correctly.

This is the situation before spam message arrives (logs are formatted with `npm start | pino-pretty`)

```
[1625728233366] DEBUG (39850 on andrisreinman): 6E STATUS "[Gmail]/Spam" (UIDNEXT MESSAGES HIGHESTMODSEQ UIDVALIDITY)
    tid: 2
    component: "imap-client"
    account: "pangalink"
    cid: "pgai2xue6r4y8zumesuq"
    sub: "imap-connection"
    src: "s"
[1625728233395] DEBUG (39850 on andrisreinman): * STATUS "[Gmail]/Spam" (HIGHESTMODSEQ 613147 MESSAGES 1 UIDNEXT 331 UIDVALIDITY 654640696)
    tid: 2
    component: "imap-client"
    account: "pangalink"
    cid: "pgai2xue6r4y8zumesuq"
    sub: "imap-connection"
    src: "s"
[1625728233396] DEBUG (39850 on andrisreinman): 6E OK Success
    tid: 2
    component: "imap-client"
    account: "pangalink"
    cid: "pgai2xue6r4y8zumesuq"
    sub: "imap-connection"
    src: "s"
```

You can see that there is 1 message. Next I send an email to that account that is flagged as Spam and wait until recurring check is made.

```
[1625728294743] DEBUG (39850 on andrisreinman): 99 STATUS "[Gmail]/Spam" (UIDNEXT MESSAGES HIGHESTMODSEQ UIDVALIDITY)
    tid: 2
    component: "imap-client"
    account: "pangalink"
    cid: "pgai2xue6r4y8zumesuq"
    sub: "imap-connection"
    src: "s"
[1625728294774] DEBUG (39850 on andrisreinman): * STATUS "[Gmail]/Spam" (HIGHESTMODSEQ 613160 MESSAGES 2 UIDNEXT 332 UIDVALIDITY 654640696)
    tid: 2
    component: "imap-client"
    account: "pangalink"
    cid: "pgai2xue6r4y8zumesuq"
    sub: "imap-connection"
    src: "s"
[1625728294774] DEBUG (39850 on andrisreinman): 99 OK Success
    tid: 2
    component: "imap-client"
    account: "pangalink"
    cid: "pgai2xue6r4y8zumesuq"
    sub: "imap-connection"
    src: "s"

[1625728294775] TRACE (39850 on andrisreinman): Requesting lock
    tid: 2
    component: "imap-client"
    account: "pangalink"
    cid: "xhl81lznjw87ic38f6qm"
    sub: "imap-connection"
    path: "[Gmail]/Spam"
    lockId: 5
[1625728294775] DEBUG (39850 on andrisreinman): 9A SELECT "[Gmail]/Spam"
    tid: 2
    component: "imap-client"
    account: "pangalink"
    cid: "pgai2xue6r4y8zumesuq"
    sub: "imap-connection"
    src: "s"
```

Now there is 2 messages listed and IMAP API immediatelly starts processing these messages

**Comment by andris9** [comment]
Btw I'm not sure if it is related or not but latest version (v1.5.4) fixes a bug with detecting deleted messages. This might affect when you delete messages immediately after receiving them.

**Comment by andris9** [comment]
Closing for now. If this is still an issue then please re-open or create a new issue.

Btw if your use case is to only detect if emails land in **INBOX or Spam** then there is another setup option (requires latest version of IMAP API):

1. Run [/v1/verifyAccount](https://imapapi.com/api.html#operation/postV1Verifyaccount) with imap config and `mailboxes:true`
2. Determine the main folder path (eg "INBOX" or "All Mail") and Spam path from the resulting `mailboxes` array
3. Register a [new account](https://imapapi.com/api.html#operation/postV1Account) for the user with `path` option set to the main folder (eg. `path: "INBOX"`), this way IMAP API starts looking for changes *only* on that folder and ignores everything else
4. Register a [second account](https://imapapi.com/api.html#operation/postV1Account) for the same user, this time with `path` option set to the spam folder (eg. `path: "[Gmail]/Spam"`)

This way you are going to set up not one but 2 IMAP connections of the same account against the IMAP server but you are going to get notifications both for INBOX and Spam messages without any delays.

**Comment by andris9** [comment]
Wrote a blog post about measuring if emails go to INBOX or to spam, available [here](https://blog.imapapi.com/measuging-inbox-spam-placement/)
