### ISSUE TITLE
IMAP API delay the webhook notifications

### ISSUE THREAD

**Issue by soumen-cn** [andris9/imapapi#73]
Hi @andris9 

what could make IMAP API delay the webhook notifications by days as we didn't have any new email (with the date) newer than 2 days ago?

Thanks
Soumen

**Comment by andris9** [comment]
Did you receive the webhook after a big delay or are you still waiting for it?

**Comment by soumen-cn** [comment]
Hi @andris9 

The webhook is being called, just the messages are very old - two days old.
In webhook today also I am getting the mail for 15th May or before that.

I have not received any webhook notification for the 16th or 17th may till now.

**Comment by soumen-cn** [comment]
Hi @andris9 

Is there's any way to limit the syncing of emails for the IMAP API to only start from the date the mailbox got connected so that the webhook event does not call for old emails?

**Comment by raduoprea** [comment]
Hi @andris9,

We've also noticed is that the number of items in Redis increased significantly since this issue appeared - went from around 35k-700k (going up and down) to 7.8M+ in one week, with just a 10% increase in the number of mailboxes connected to this server.

Have any idea what might have caused it?

**Comment by andris9** [comment]
IMAP API stores 2 redis keys for every folder in a email account. So an account with 100 folders would generate 200 keys in Redis, one HASH and one ZSET. If you dare then you could run `KEYS iam:*` in your Redis server to see how many folder keys there are. This might take a lot of time and as Redis is single threaded then no other command can be executed until KEYS has finished)

The other thing that might generate a lot of keys in Redis is the queueing system. You can see the keys by running `KEYS bull:*` in your Redis server. There should not be many jobs so having a large number of such keys would mean that something is wrong with job processing. There is a separate job for every webhook notification and if webhooks are failing (eg. the URL is invalid etc.) then these jobs might pile up.

**Comment by raduoprea** [comment]
Thanks for your quick reply @andris9.

Of course, it's so obvious now, it was Bull - there were some webhook events that we weren't returning a 200 for, so they kept pilling up, and probably they were delaying the messageNew events we were expecting.

I assume once the queue gets processed, we'll see the emails catch up to the current day.

I'll close the issue once we've given it some time.

**Comment by raduoprea** [comment]
@andris9 All good now, back on track and processing emails, closing the issue.
