### ISSUE TITLE
Plans to support moving messages

### ISSUE THREAD

**Issue by midgethoen** [andris9/imapapi#8]
first things first. awesome project!
I've been tinkering with it for some personal automation today and Im really excited!

I noticed that the swagger docs dont mention any way of moving messages between boxes, however [imapflow](https://imapflow.com/module-imapflow-ImapFlow.html#messageMove) does seem to support this.  

is this possible with imapapi? Is something like this in the making? or can i perhaps contribute to make this possible?

Cheers,

Midge

**Comment by andris9** [comment]
The latest commit includes a new method to move a message.

> NB! Currently all message methods apply to single messages, that also includes the new move method. You can not move a range of messages with a single API call - just one specific message.

<img width="669" alt="Screenshot 2020-04-09 at 17 53 33" src="https://user-images.githubusercontent.com/132242/78908645-0f107100-7a8b-11ea-943c-205b075303b0.png">

**Comment by midgethoen** [comment]
Awesome, thnx!
